version: "2"

services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
    - ./fixture.sh:/docker-entrypoint-initdb.d/fixture.sh
    labels:
      com.dnsdock.alias: postgres.pgdumpacl.docker

  build:
    image: dalibo/postgres-sdk
    environment:
      HISTFILE: /workspace/.docker-bash-history
      PGHOST: postgres
      PGUSER: postgres
    volumes:
    - .:/workspace
    command: "tail -f /dev/null"
