version: "2"

services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
    - ./fixture.sh:/docker-entrypoint-initdb.d/fixture.sh
    labels:
      com.dnsdock.alias: postgres.pgdumpacl.docker

  build:
    image: dalibo/postgres-sdk
    environment:
      HISTFILE: /workspace/.docker-build-bash-history
      PGHOST: postgres
      PGUSER: postgres
    volumes:
    - .:/workspace
    links:
    - postgres
    command: "tail -f /dev/null"

  rpm:
    image: rpmbuild/centos7
    environment:
    - HISTFILE=/srv/.docker-rpm-bash-history
    - PGDG_RPM
    - PGVERSION
    volumes:
    - .:/srv
